### ISSUE TITLE
Error running process command on Azure Kinect data

### ISSUE THREAD

**Issue by JesseDill** [SpectacularAI/sdk-examples#127]
On Ubuntu 20.04.5 LTS, after running: `sai-cli process INPUT_PATH --key_frame_distance=0.05 /example/output/path/my-nerf`

I get this output

> 
> Selected device type: k4a
> parameterSets: ["wrapper-base", "k4a", "icp"]
> {'maxMapSize': 0, 'useSlam': True, 'passthroughColorImages': True, 'keyframeDecisionDistanceThreshold': 0.05, 'icpVoxelSize': 0.05}
> SpectacularAI WARN: Long gap in the data: 3.829903 seconds
> warning: Lost tracking!
> warning: Lost tracking!
> warning: Lost tracking!
> SpectacularAI WARN: Discarding a bad frame 1909 of camera 0.
> SpectacularAI WARN: Discarding a bad frame 1909 of camera 1.
> terminate called after throwing an instance of 'pybind11::error_already_set'
>   what():  OSError: [Errno 18] Invalid cross-device link: '/tmp/tmp2asf_mw7/frame_00001.jpg' -> 'output/images/frame_00000.jpg'
> 
> At:
>   /home/jdill/miniconda3/envs/nvf/lib/python3.10/site-packages/spectacularAI/cli/process/process.py(393): onMappingOutput
> 
> Aborted (core dumped)

Any idea what the issue is?

**Comment by kaatrasa** [comment]
Thanks for reporting the issue! I was able to reproduce it, and there will be a fix in the next patch release. 

For now, could you either use previous version of spectacularAI pypi package or make sure that the `sai-cli` output directory is using the same disk as the Python's `tempfile.mkdtemp();`

**Comment by JesseDill** [comment]
Thank you!
