### ISSUE TITLE
Could not open data.jsonl

### ISSUE THREAD

**Issue by khushalrs** [SpectacularAI/sdk-examples#131]
I just installed the spectacularAI using `pip install spectacularai[full]` 
When I run the `sai-cli  process` command it given me the following error

![image](https://github.com/SpectacularAI/sdk-examples/assets/63808636/4714a5dd-0aac-4138-8dd7-336500fe6c91)

**Comment by tjucaokun** [comment]
same problem. Have you solved it?

**Comment by khushalrs** [comment]
Nope unable to resolve the error

**Comment by kaatrasa** [comment]
Hey, sorry for the late reply, we have been quite busy.

I wasn't able to reproduce this issue with Windows 10 or Windows 11 using PowerShell.

1) Could you say which terminal you are using? (maybe miniconda's terminal?) and could you try with PowerShell and Git Bash instead.
2) Do the other [Python examples](https://github.com/SpectacularAI/sdk-examples/blob/main/python/oak/mapping_visu.py) work for you: For instance, `python mapping_visu.py --dataFolder /path/to/data`
3) Could be some issue with Python's `tempfile`, based on your error message. Could you check if the data.jsonl file mentioned in the ERROR message exists? We will try to get rid of it in next release.

**Comment by kaatrasa** [comment]
This issue might have been fixed with release 1.31.0, just run `pip install spectacularai[full] --force`
