### ISSUE TITLE
How to sava real-time point cloud

### ISSUE THREAD

**Issue by GH-Fonic** [SpectacularAI/sdk-examples#145]
Thanks to the Spectacular AI team's work, I love ORBBEC's reconstruction of the dense point cloud in sai-record-orbbec, but I don't see how to save the dense point cloud in ply or pcd with python, I don't see that in the documentation. I hope you can answer this question and thank the Spectacular AI team for their work :)

**Comment by kaatrasa** [comment]
Hey, 

the `sai-record-orbbec` tool is mainly meant for recording with live preview and currently doesn't have an option to save the point cloud. Instead, I recommend you would use our `sai-cli process` commandline tool (installed with `pip install spectacularai[full]`).

To replay the dataset (with optimized parameters for offline use) and save the pointcloud, you can run:
`sai-cli process /path/to/recording /path/to/output/pointcloud.ply --preview3d`

You can see all the options with `--help`.

**Comment by GH-Fonic** [comment]
thanks,I see. Thanks again for your work.
:)
