### ISSUE TITLE
pip installtion of spectacularAI not working on ubuntu 18.04

### ISSUE THREAD

**Issue by Captain299792458** [SpectacularAI/sdk-examples#26]
I am trying to install spectacularAI in ubuntu 18.04, but I am getting following error

```
Could not find a version that satisfies the requirement spectacularAI (from versions: )
No matching distribution found for spectacularAI
```
Please let me know how do you install this package ? Its written on their webiste that it will work on ubuntu 18 + 
Thanks!

**Comment by oseiskar** [comment]
You are probably trying to use it on ARM? The aarch64 version is available with a commercial license. See https://www.spectacularai.com/#product

**Comment by Captain299792458** [comment]
Thanks, I sent you email regarding this
