### ISSUE TITLE
Not able run vio_mapper in Linux_ubuntu_x86-64

### ISSUE THREAD

**Issue by woshicaijihahahaha** [SpectacularAI/sdk-examples#34]
hello,when i was running  ./vio_mapper /home/yy/EDisk/recording/  from the Linux_Ubuntu_x86-64 release (spectacularAI_realsensePlugin_cpp_non-commercial_1.2.0)

then some wrong messages occured :
SpectacularAI WARN: Unknown camera model RS2_DISTORTION_INVERSE_BROWN_CONRADY, ignoring distortion coefficients.
SpectacularAI WARN: Unknown camera model RS2_DISTORTION_BROWN_CONRADY, ignoring distortion coefficients.
terminate called after throwing an instance of 'std::runtime_error'
  what():  unused key(s): icpMinOverlapRatio

so can you help me fix it please.

**Comment by pekkaran** [comment]
Please remove from `recording/vio_config.yaml` the line that starts with `icpMinOverlapRatio:`.

The warnings about distortion can be ignored, the RealSense video inputs are rectified or closely so and the default pinhole model without distortion should work well.

**Comment by woshicaijihahahaha** [comment]
Hello ，I found the following in the **vio_config.yaml file**：

noiseScale: 500
trackMinFrames: 3
trackChiTestOutlierR: 3
trackOutlierThresholdGrowthFactor: 1.3
hybridMapSize: 2
sampleSyncLag: 1
estimateImuCameraTimeShift:  
outputCameraPose: True
imuStationaryEnabled: True
trackingStatusInitMinSeconds: 0.5
useGnss: true
imuStationaryEnabled: False
trackingStatusInitMinSeconds: 2.0
skipFirstNCandidates: 10
noiseProcessBGA: 1e-5
visualR: 0.01
cameraTrailLength: 12
cameraTrailHanoiLength: 8

I didn't find the *icpMinOverlapRatio* you mentioned,I am still a newbie in these areas，Can you look at it again for me?

**Comment by pekkaran** [comment]
Sorry, I misunderstood your issue. The problem has been fixed in the [1.3.0 release](https://github.com/SpectacularAI/sdk/releases). Could you try again with that version?
