### ISSUE TITLE
Meet trouble when I use OAK-D-PoE with python example

### ISSUE THREAD

**Issue by JimXu1989** [SpectacularAI/sdk-examples#42]
Hi, 
When I use an OAK-D-PoE with python example, I met some error, it seems PoE devices do not compatible with python sdk :
Starting OAK-D device
Close the window to stop mapping
Spectacular AI SDK: WARN: unrecoginzed OAK board name 'OAK-D-POE'
you may need to manually set IMU-to-camera extrinsics (configuration.imuToCameraLeft)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "mapping_visu.py", line 244, in captureLoop
    vioPipeline.startSession(device) as vio_session:
RuntimeError: Spectacular AI SDK:  error: LOW USB SPEED!

############################################################################
Your USB connection speed 'UNKNOWN' is lower than required.
Please check that you have connected the device to an USB 3 port with an
undamaged USB 3 cable (blue interior). Speed SUPER or better is recommended.
Disable this check by setting config.ensureSufficientUsbSpeed to false.
############################################################################

^CTraceback (most recent call last):
  File "mapping_visu.py", line 252, in <module>
    visu3D.run()
  File "mapping_visu.py", line 124, in run
    time.sleep(0.01)
KeyboardInterrupt

**Comment by jeskesen** [comment]
I have had success using an OAK-D-PoE by adding the following line during the pipeline setup.

`config.ensureSufficientUsbSpeed = False
`
