### ISSUE TITLE
vio_gnss.py

### ISSUE THREAD

**Issue by RamatovInomjon** [SpectacularAI/sdk-examples#55]
Hi @Bercon , how to create GPS aided vio with this sdk examples, https://www.youtube.com/watch?v=MSBGzktEVQg here is your examples , as I understand vio_gnss.py script gives GNSS VIO estimation , is it right?

**Comment by Bercon** [comment]
vio_gnss.py is an example how to provide GPS locations to the SDK. You must implement the software that obtains the GPS locations and formats them before sending them to our SDK. The tools used to do the visualization in the YouTube video aren't public, but the SDK output contains all the information you would need to draw the trajectory, orientation and uncertainty circle
