### ISSUE TITLE
Modify the frame rate of the OAK-D-PRO-W camera

### ISSUE THREAD

**Issue by liang-zijian** [SpectacularAI/sdk-examples#74]
I tested VIO with indoor lighting and found significant drift. However, results are stable in outdoor natural light. I noticed that the Oak camera flickered under the indoor strobe light. 

Does this SDK support modifying the frame rate or exposure time of the OAK camera to solve the strobe problem? 

Can you give an example of how to change it? Thank you so much!

**Comment by oseiskar** [comment]
Hi. You can modify the FPS of the cameras using the Depth AI methods by modifying the example codes as follows
```python
vio_pipeline = spectacularAI.depthai.Pipeline(pipeline)
changed_fps = 25 # new
vio_pipeline.monoLeft.setFps(changed_fps) # new
vio_pipeline.monoRight.setFps(changed_fps) # new
```
There is also a new configuration flag called [`useVioAutoExposure`](https://spectacularai.github.io/docs/sdk/python/latest/#spectacularAI.depthai.Configuration.useVioAutoExposure) that can reduce motion blur in low-light and indoor conditions.  It can be enabled as
```python
vio_pipeline = spectacularAI.depthai.Pipeline(pipeline, useVioAutoExposure=True)
```
