### ISSUE TITLE
Installing Pypi spectacularAI on a raspberry pi

### ISSUE THREAD

**Issue by hidara2000** [SpectacularAI/sdk-examples#82]
Hey,
Is there any way to install the spectacularAI library on a pi?

getting a
ERROR: Could not find a version that satisfies the requirement spectacularAI (from versions: none)

when installing with pip

python 3.10

works on windows

Cheers

**Comment by oseiskar** [comment]
The PI version is a commercial product, contact sales at https://www.spectacularai.com/#contact
