### ISSUE TITLE
Spectacular SDK mapping_visu.py is dropping frames of OAK-D

### ISSUE THREAD

**Issue by ostepan2006** [SpectacularAI/sdk-examples#87]
Hello Team. I had been tryng Spectacular SDK `mapping_visu.py` with OAK-D and got tons of messages "SpectacularAI : dropping frames! VIO is running too slow or data is being input too fast". Also I got a message: IMU firmware version detected : 3.2.13 is not supported. Latest supported: 3.9.9. Use "imu.enableFirmwareUpdate(True)"once to update firmware to latest". I had update imu firmware version. But the message "SpectacularAI : dropping frames! VIO is running too slow or data is being input too fast" has not dissapeared.

I had been using Asus notebook with Core i5 and 4 Gb RAM. Might this mean that capability of my notebook are poor for Spectacular SDK examples?

Thanks.

**Comment by ostepan2006** [comment]
Hi Team. I had resolved the issue. Thanks. I would had been deleted this request but there is no oppurtunitie.

**Comment by Contain1R** [comment]
> 大家好。我已经解决了这个问题。谢谢。我本来会删除这个请求，但没有机会。

怎么解决的呀

**Comment by Contain1R** [comment]
> Hi Team. I had resolved the issue. Thanks. I would had been deleted this request but there is no oppurtunitie.

how to resolved？

**Comment by ajsnyde** [comment]
@ostepan2006 
How did you resolve it???
