### ISSUE TITLE
[QUESTION] Is their a way to get the VIO offline using prerecorded stereo images and imu data?

### ISSUE THREAD

**Issue by y2d2** [SpectacularAI/sdk-examples#90]
Dear, 

Is it possible to use the spectacularAI SDK to calculate VIO with the oakd-pro camera (with BMI270 IMU), when the rectified stereo images and the imu have been prerecorded with a certain timestamp? 

If so what information would all be required to do this? 

Kind regards, 

YD

**Comment by oseiskar** [comment]
Yes, it is possible with the publicly available SDK if you record the data through our Python recording tool https://github.com/SpectacularAI/sdk-examples/blob/main/python/oak/vio_record.py . Replay API example here https://github.com/SpectacularAI/sdk-examples/blob/main/python/oak/vio_replay.py.

If the data is recorded in another format, you need to use our core SDK, which is available as a paid product (through sales: https://www.spectacularai.com/#contact)
